const fs = require('fs');
const path = require('path');
const { toKebab } = require('./config-utils');

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function resetDir(dirPath) {
  fs.rmSync(dirPath, { recursive: true, force: true });
  fs.mkdirSync(dirPath, { recursive: true });
}

function commandToMethodName(commandName) {
  return String(commandName)
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((part, index) => {
      const lower = part.toLowerCase();
      return index === 0 ? lower : lower[0].toUpperCase() + lower.slice(1);
    })
    .join('');
}

function renderPackageJson(config) {
  const packageJson = {
    name: `${toKebab(config.name)}-cli`,
    version: config.version,
    description: `${config.name} CLI generated by AgentBridge`,
    license: 'MIT',
    type: 'commonjs',
    bin: {
      [toKebab(config.name)]: `./bin/${toKebab(config.name)}.js`
    },
    scripts: {
      start: `node ./bin/${toKebab(config.name)}.js`
    },
    dependencies: {
      commander: '^12.1.0'
    }
  };

  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

function renderOutputLib() {
  return `function json(data, pretty) {
  const text = pretty ? JSON.stringify(data, null, 2) : JSON.stringify(data);
  process.stdout.write(text + '\\n');
}

function error(payload, pretty) {
  const envelope = {
    error: true,
    code: payload.code || 'REQUEST_FAILED',
    message: payload.message || 'Request failed',
    details: payload.details || {}
  };

  const text = pretty ? JSON.stringify(envelope, null, 2) : JSON.stringify(envelope);
  process.stderr.write(text + '\\n');
}

module.exports = {
  json,
  error
};
`;
}

function renderClientLib(config) {
  const authConfig = JSON.stringify(config.auth || { credentials: [] }, null, 2);

  return `const fs = require('fs');

function toKebab(name) {
  return String(name)
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function toCamelCase(name) {
  return String(name).replace(/[-_]+([a-zA-Z0-9])/g, (_m, g1) => g1.toUpperCase());
}

function readOption(options, name) {
  if (Object.prototype.hasOwnProperty.call(options, name)) {
    return options[name];
  }

  const camel = toCamelCase(name);
  if (Object.prototype.hasOwnProperty.call(options, camel)) {
    return options[camel];
  }

  return undefined;
}

function coerceValue(value, type) {
  if (value === undefined || value === null || value === '') {
    return value;
  }

  if (type === 'number') {
    const parsed = Number(value);
    if (Number.isNaN(parsed)) {
      throw new Error(\`Expected number but received: \${value}\`);
    }
    return parsed;
  }

  if (type === 'boolean') {
    if (typeof value === 'boolean') {
      return value;
    }

    const normalized = String(value).toLowerCase();
    if (normalized === 'true' || normalized === '1') {
      return true;
    }

    if (normalized === 'false' || normalized === '0') {
      return false;
    }

    throw new Error(\`Expected boolean but received: \${value}\`);
  }

  return String(value);
}

function parseJsonText(raw, label) {
  try {
    return JSON.parse(raw);
  } catch (_error) {
    throw new Error(\`Invalid JSON for \${label}\`);
  }
}

function parseJsonBody(rawBody) {
  if (rawBody === undefined || rawBody === null || rawBody === '') {
    return null;
  }

  return parseJsonText(rawBody, '--body');
}

function parseBodyFromStdin(enabled) {
  if (!enabled) {
    return null;
  }

  const raw = fs.readFileSync(0, 'utf8').trim();
  if (!raw) {
    throw new Error('Expected JSON on stdin because --body-stdin was provided');
  }

  return parseJsonText(raw, '--body-stdin');
}

function buildRequestBody(command, options) {
  const requestBody = command.requestBody || null;
  if (!requestBody) {
    return null;
  }

  const direct = parseJsonBody(readOption(options, 'body'));
  const stdin = parseBodyFromStdin(Boolean(readOption(options, 'body-stdin')));

  if (direct !== null && stdin !== null) {
    throw new Error('Use either --body or --body-stdin, not both');
  }

  const properties = requestBody.properties || {};
  const hasBodyProps = Object.keys(properties).length > 0;

  let payload = direct !== null ? direct : stdin !== null ? stdin : hasBodyProps ? {} : null;
  if (payload !== null && (typeof payload !== 'object' || Array.isArray(payload))) {
    throw new Error('Request body must be a JSON object');
  }

  if (payload === null && requestBody.required) {
    throw new Error('Missing required request body. Provide --body, --body-stdin, or body field flags.');
  }

  let hadBodyFlag = false;
  Object.entries(properties).forEach(([propName, schema]) => {
    const optionName = \`body-\${toKebab(propName)}\`;
    const raw = readOption(options, optionName);
    if (raw === undefined || raw === null || raw === '') {
      return;
    }

    if (payload === null) {
      payload = {};
    }

    payload[propName] = coerceValue(raw, schema.type);
    hadBodyFlag = true;
  });

  if (hasBodyProps) {
    if (payload === null) {
      payload = {};
    }

    Object.entries(properties).forEach(([propName, schema]) => {
      if (!schema.required) {
        return;
      }

      if (!Object.prototype.hasOwnProperty.call(payload, propName) || payload[propName] === undefined || payload[propName] === null || payload[propName] === '') {
        const optionName = \`--body-\${toKebab(propName)}\`;
        throw new Error(\`Missing required request body field: \${optionName}\`);
      }
    });
  }

  if (payload !== null) {
    const isEmptyObject = typeof payload === 'object' && !Array.isArray(payload) && Object.keys(payload).length === 0;
    if (isEmptyObject && !requestBody.required && !hadBodyFlag && direct === null && stdin === null) {
      return null;
    }
  }

  return payload;
}

async function request(command, options) {
  const auth = ${authConfig};
  const params = new URLSearchParams();
  const commandParams = command.params || {};
  let resolvedPath = command.path;
  const headers = {
    accept: 'application/json'
  };

  (auth.credentials || []).forEach((credential) => {
    const envValue = process.env[credential.envVar];

    if (!envValue) {
      throw new Error(\`Missing required auth environment variable: \${credential.envVar}\`);
    }

    const authValue = credential.prefix ? \`\${credential.prefix}\${envValue}\` : envValue;

    if (credential.in === 'header') {
      headers[credential.name] = authValue;
      return;
    }

    params.append(credential.name, authValue);
  });

  Object.entries(commandParams).forEach(([name, schema]) => {
    const raw = readOption(options, name);

    if ((raw === undefined || raw === null || raw === '') && schema.required) {
      throw new Error(\`Missing required parameter: --\${name}\`);
    }

    if (raw === undefined || raw === null || raw === '') {
      return;
    }

    const value = coerceValue(raw, schema.type);
    const token = \`{\${name}}\`;

    if (resolvedPath.includes(token)) {
      resolvedPath = resolvedPath.replaceAll(token, encodeURIComponent(String(value)));
      return;
    }

    params.append(name, String(value));
  });

  const query = params.toString();
  const url = '${config.apiBase}' + resolvedPath + (query ? '?' + query : '');
  const requestBody = buildRequestBody(command, options);

  if (requestBody !== null) {
    headers['content-type'] = 'application/json';
  }

  const response = await fetch(url, {
    method: command.method,
    headers,
    body: requestBody !== null ? JSON.stringify(requestBody) : undefined
  });

  const text = await response.text();
  let responseBody = text;

  try {
    responseBody = text ? JSON.parse(text) : null;
  } catch (_err) {
    responseBody = text;
  }

  if (!response.ok) {
    const error = new Error(\`HTTP \${response.status}\`);
    error.statusCode = response.status;
    error.responseBody = responseBody;
    throw error;
  }

  return responseBody;
}

module.exports = {
  request
};
`;
}

function renderCommandModule(command) {
  const functionName = commandToMethodName(command.name);
  const serializedCommand = JSON.stringify(command, null, 2);

  return `const { request } = require('../lib/client');
const output = require('../lib/output');

const command = ${serializedCommand};

async function ${functionName}(options) {
  try {
    if (command.method !== 'GET' && !options.yes) {
      throw new Error('This operation changes state. Re-run with --yes to confirm.');
    }

    const data = await request(command, options);
    output.json(data, Boolean(options.pretty));
  } catch (error) {
    output.error(
      {
        code: error.statusCode ? 'HTTP_ERROR' : 'REQUEST_FAILED',
        message: error.message,
        details: {
          statusCode: error.statusCode || null,
          command: command.name
        }
      },
      Boolean(options.pretty)
    );
    process.exit(1);
  }
}

module.exports = {
  run: ${functionName},
  command
};
`;
}

function renderBinFile(config) {
  const imports = config.commands
    .map((command, index) => {
      const varName = `cmd${index}`;
      return `const ${varName} = require('../commands/${toKebab(command.name)}');`;
    })
    .join('\n');

  const registrations = config.commands
    .map((command, index) => {
      const varName = `cmd${index}`;
      const params = command.params || {};
      const paramOptions = Object.entries(params)
        .map(([paramName, schema]) => {
          const flagName = `--${toKebab(paramName)} <value>`;
          const desc = schema.description || `${paramName} parameter`;
          return `  .option('${flagName}', '${desc}')`;
        })
        .join('\n');

      const bodyProps = (command.requestBody && command.requestBody.properties) || {};
      const bodyOptions = Object.entries(bodyProps)
        .map(([propName, schema]) => {
          const flagName = `--body-${toKebab(propName)} <value>`;
          const req = schema.required ? 'required' : 'optional';
          const desc = schema.description || `${propName} body field`;
          return `  .option('${flagName}', '${desc} (${req})')`;
        })
        .join('\n');

      const mutationOptions = command.method !== 'GET'
        ? [
            `  .option('--yes', 'Confirm non-GET operation')`,
            command.requestBody ? `  .option('--body <json>', 'Raw JSON request body')` : null,
            command.requestBody ? `  .option('--body-stdin', 'Read JSON body from stdin')` : null,
            bodyOptions || null
          ].filter(Boolean).join('\n')
        : '';

      return `program
  .command('${command.name}')
  .description('${command.description.replace(/'/g, "\\'")}')
${paramOptions ? `${paramOptions}\n` : ''}${mutationOptions ? `${mutationOptions}\n` : ''}  .option('--pretty', 'Pretty-print JSON')
  .action((options) => ${varName}.run(options));`;
    })
    .join('\n\n');

  return `#!/usr/bin/env node

const { Command } = require('commander');

${imports}

const program = new Command();

program
  .name('${toKebab(config.name)}')
  .description('${config.name} CLI generated by AgentBridge')
  .version('${config.version}');

${registrations}

program.parse(process.argv);
`;
}

function renderReadme(config) {
  const commandList = config.commands
    .map((command) => `- \`${toKebab(config.name)} ${command.name}\` - ${command.description}`)
    .join('\n');
  const authVars = (config.auth && Array.isArray(config.auth.credentials))
    ? config.auth.credentials.map((credential) => credential.envVar)
    : [];
  const uniqueAuthVars = [...new Set(authVars)];
  const authSection = uniqueAuthVars.length
    ? `## Auth\n\nSet required environment variables before running commands:\n\n${uniqueAuthVars.map((envVar) => `- \`${envVar}\``).join('\n')}\n\nDo not pass secrets as command flags.\n\n`
    : '';

  return `# ${config.name} CLI

Generated by AgentBridge (api-to-cli).

## Install

\`\`\`bash
npm install
npm link
\`\`\`

${authSection}## Commands

${commandList}
`;
}

function writeFile(filePath, content, executable = false) {
  fs.writeFileSync(filePath, content, 'utf8');
  if (executable) {
    fs.chmodSync(filePath, 0o755);
  }
}

function generateCliProject({ config, outputPath }) {
  const binName = toKebab(config.name);
  const binDir = path.join(outputPath, 'bin');
  const commandsDir = path.join(outputPath, 'commands');
  const libDir = path.join(outputPath, 'lib');

  ensureDir(outputPath);
  resetDir(binDir);
  resetDir(commandsDir);
  resetDir(libDir);

  writeFile(path.join(outputPath, 'package.json'), renderPackageJson(config));
  writeFile(path.join(outputPath, 'README.md'), renderReadme(config));
  writeFile(path.join(libDir, 'output.js'), renderOutputLib());
  writeFile(path.join(libDir, 'client.js'), renderClientLib(config));
  writeFile(path.join(binDir, `${binName}.js`), renderBinFile(config), true);

  config.commands.forEach((command) => {
    writeFile(
      path.join(commandsDir, `${toKebab(command.name)}.js`),
      renderCommandModule(command)
    );
  });
}

module.exports = {
  generateCliProject
};
