const fs = require('fs');
const path = require('path');
const { toKebab } = require('./config-utils');

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function commandToMethodName(commandName) {
  return String(commandName)
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((part, index) => {
      const lower = part.toLowerCase();
      return index === 0 ? lower : lower[0].toUpperCase() + lower.slice(1);
    })
    .join('');
}

function renderPackageJson(config) {
  const packageJson = {
    name: `${toKebab(config.name)}-cli`,
    version: config.version,
    description: `${config.name} CLI generated by AgentBridge`,
    license: 'MIT',
    type: 'commonjs',
    bin: {
      [toKebab(config.name)]: `./bin/${toKebab(config.name)}.js`
    },
    scripts: {
      start: `node ./bin/${toKebab(config.name)}.js`
    },
    dependencies: {
      commander: '^12.1.0'
    }
  };

  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

function renderOutputLib() {
  return `function json(data, pretty) {
  const text = pretty ? JSON.stringify(data, null, 2) : JSON.stringify(data);
  process.stdout.write(text + '\\n');
}

function error(payload, pretty) {
  const envelope = {
    error: true,
    code: payload.code || 'REQUEST_FAILED',
    message: payload.message || 'Request failed',
    details: payload.details || {}
  };

  const text = pretty ? JSON.stringify(envelope, null, 2) : JSON.stringify(envelope);
  process.stderr.write(text + '\\n');
}

module.exports = {
  json,
  error
};
`;
}

function renderClientLib(config) {
  const authConfig = JSON.stringify(config.auth || { credentials: [] }, null, 2);

  return `async function request(command, options) {
  const auth = ${authConfig};
  const params = new URLSearchParams();
  const commandParams = command.params || {};
  let resolvedPath = command.path;
  const headers = {
    accept: 'application/json'
  };

  (auth.credentials || []).forEach((credential) => {
    const envValue = process.env[credential.envVar];

    if (!envValue) {
      throw new Error(\`Missing required auth environment variable: \${credential.envVar}\`);
    }

    const authValue = credential.prefix ? \`\${credential.prefix}\${envValue}\` : envValue;

    if (credential.in === 'header') {
      headers[credential.name] = authValue;
      return;
    }

    params.append(credential.name, authValue);
  });

  Object.entries(commandParams).forEach(([name, schema]) => {
    const value = options[name];

    if ((value === undefined || value === null || value === '') && schema.required) {
      throw new Error(\`Missing required parameter: --\${name}\`);
    }

    if (value === undefined || value === null || value === '') {
      return;
    }

    const token = \`{\${name}}\`;

    if (resolvedPath.includes(token)) {
      resolvedPath = resolvedPath.replaceAll(token, encodeURIComponent(String(value)));
      return;
    }

    params.append(name, String(value));
  });

  const query = params.toString();
  const url = '${config.apiBase}' + resolvedPath + (query ? '?' + query : '');

  const response = await fetch(url, {
    method: command.method,
    headers
  });

  const text = await response.text();
  let body = text;

  try {
    body = text ? JSON.parse(text) : null;
  } catch (_err) {
    body = text;
  }

  if (!response.ok) {
    const error = new Error(\`HTTP \${response.status}\`);
    error.statusCode = response.status;
    error.responseBody = body;
    throw error;
  }

  return body;
}

module.exports = {
  request
};
`;
}

function renderCommandModule(command) {
  const functionName = commandToMethodName(command.name);
  const serializedCommand = JSON.stringify(command, null, 2);

  return `const { request } = require('../lib/client');
const output = require('../lib/output');

const command = ${serializedCommand};

async function ${functionName}(options) {
  try {
    const data = await request(command, options);
    output.json(data, Boolean(options.pretty));
  } catch (error) {
    output.error(
      {
        code: error.statusCode ? 'HTTP_ERROR' : 'REQUEST_FAILED',
        message: error.message,
        details: {
          statusCode: error.statusCode || null,
          command: command.name
        }
      },
      Boolean(options.pretty)
    );
    process.exit(1);
  }
}

module.exports = {
  run: ${functionName},
  command
};
`;
}

function renderBinFile(config) {
  const imports = config.commands
    .map((command, index) => {
      const varName = `cmd${index}`;
      return `const ${varName} = require('../commands/${toKebab(command.name)}');`;
    })
    .join('\n');

  const registrations = config.commands
    .map((command, index) => {
      const varName = `cmd${index}`;
      const params = command.params || {};
      const options = Object.entries(params)
        .map(([paramName, schema]) => {
          const flagName = `--${toKebab(paramName)} <value>`;
          const desc = schema.description || `${paramName} parameter`;
          return `  .option('${flagName}', '${desc}')`;
        })
        .join('\n');

      return `program
  .command('${command.name}')
  .description('${command.description.replace(/'/g, "\\'")}')
${options ? `${options}\n` : ''}  .option('--pretty', 'Pretty-print JSON')
  .action((options) => ${varName}.run(options));`;
    })
    .join('\n\n');

  return `#!/usr/bin/env node

const { Command } = require('commander');

${imports}

const program = new Command();

program
  .name('${toKebab(config.name)}')
  .description('${config.name} CLI generated by AgentBridge')
  .version('${config.version}');

${registrations}

program.parse(process.argv);
`;
}

function renderReadme(config) {
  const commandList = config.commands
    .map((command) => `- \`${toKebab(config.name)} ${command.name}\` - ${command.description}`)
    .join('\n');
  const authVars = (config.auth && Array.isArray(config.auth.credentials))
    ? config.auth.credentials.map((credential) => credential.envVar)
    : [];
  const uniqueAuthVars = [...new Set(authVars)];
  const authSection = uniqueAuthVars.length
    ? `## Auth\n\nSet required environment variables before running commands:\n\n${uniqueAuthVars.map((envVar) => `- \`${envVar}\``).join('\n')}\n\nDo not pass secrets as command flags.\n\n`
    : '';

  return `# ${config.name} CLI

Generated by AgentBridge (api-to-cli).

## Install

\`\`\`bash
npm install
npm link
\`\`\`

${authSection}## Commands

${commandList}
`;
}

function writeFile(filePath, content, executable = false) {
  fs.writeFileSync(filePath, content, 'utf8');
  if (executable) {
    fs.chmodSync(filePath, 0o755);
  }
}

function generateCliProject({ config, outputPath }) {
  const binName = toKebab(config.name);
  const binDir = path.join(outputPath, 'bin');
  const commandsDir = path.join(outputPath, 'commands');
  const libDir = path.join(outputPath, 'lib');

  ensureDir(outputPath);
  ensureDir(binDir);
  ensureDir(commandsDir);
  ensureDir(libDir);

  writeFile(path.join(outputPath, 'package.json'), renderPackageJson(config));
  writeFile(path.join(outputPath, 'README.md'), renderReadme(config));
  writeFile(path.join(libDir, 'output.js'), renderOutputLib());
  writeFile(path.join(libDir, 'client.js'), renderClientLib(config));
  writeFile(path.join(binDir, `${binName}.js`), renderBinFile(config), true);

  config.commands.forEach((command) => {
    writeFile(
      path.join(commandsDir, `${toKebab(command.name)}.js`),
      renderCommandModule(command)
    );
  });
}

module.exports = {
  generateCliProject
};
